// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	consent "github.com/raystack/frontier/core/consent"
	mock "github.com/stretchr/testify/mock"
)

// ConsentService is an autogenerated mock type for the ConsentService type
type ConsentService struct {
	mock.Mock
}

type ConsentService_Expecter struct {
	mock *mock.Mock
}

func (_m *ConsentService) EXPECT() *ConsentService_Expecter {
	return &ConsentService_Expecter{mock: &_m.Mock}
}

// Documents provides a mock function with no fields
func (_m *ConsentService) Documents() []consent.Document {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Documents")
	}

	var r0 []consent.Document
	if rf, ok := ret.Get(0).(func() []consent.Document); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]consent.Document)
		}
	}

	return r0
}

// ConsentService_Documents_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Documents'
type ConsentService_Documents_Call struct {
	*mock.Call
}

// Documents is a helper method to define mock.On call
func (_e *ConsentService_Expecter) Documents() *ConsentService_Documents_Call {
	return &ConsentService_Documents_Call{Call: _e.mock.On("Documents")}
}

func (_c *ConsentService_Documents_Call) Run(run func()) *ConsentService_Documents_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ConsentService_Documents_Call) Return(_a0 []consent.Document) *ConsentService_Documents_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ConsentService_Documents_Call) RunAndReturn(run func() []consent.Document) *ConsentService_Documents_Call {
	_c.Call.Return(run)
	return _c
}

// NewConsentService creates a new instance of ConsentService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewConsentService(t interface {
	mock.TestingT
	Cleanup(func())
}) *ConsentService {
	mock := &ConsentService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
