// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	orgpats "github.com/raystack/frontier/core/aggregates/orgpats"
	mock "github.com/stretchr/testify/mock"

	rql "github.com/raystack/salt/rql"
)

// OrgPATsService is an autogenerated mock type for the OrgPATsService type
type OrgPATsService struct {
	mock.Mock
}

type OrgPATsService_Expecter struct {
	mock *mock.Mock
}

func (_m *OrgPATsService) EXPECT() *OrgPATsService_Expecter {
	return &OrgPATsService_Expecter{mock: &_m.Mock}
}

// Search provides a mock function with given fields: ctx, orgID, query
func (_m *OrgPATsService) Search(ctx context.Context, orgID string, query *rql.Query) (orgpats.OrganizationPATs, error) {
	ret := _m.Called(ctx, orgID, query)

	if len(ret) == 0 {
		panic("no return value specified for Search")
	}

	var r0 orgpats.OrganizationPATs
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *rql.Query) (orgpats.OrganizationPATs, error)); ok {
		return rf(ctx, orgID, query)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, *rql.Query) orgpats.OrganizationPATs); ok {
		r0 = rf(ctx, orgID, query)
	} else {
		r0 = ret.Get(0).(orgpats.OrganizationPATs)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, *rql.Query) error); ok {
		r1 = rf(ctx, orgID, query)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// OrgPATsService_Search_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Search'
type OrgPATsService_Search_Call struct {
	*mock.Call
}

// Search is a helper method to define mock.On call
//   - ctx context.Context
//   - orgID string
//   - query *rql.Query
func (_e *OrgPATsService_Expecter) Search(ctx interface{}, orgID interface{}, query interface{}) *OrgPATsService_Search_Call {
	return &OrgPATsService_Search_Call{Call: _e.mock.On("Search", ctx, orgID, query)}
}

func (_c *OrgPATsService_Search_Call) Run(run func(ctx context.Context, orgID string, query *rql.Query)) *OrgPATsService_Search_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(*rql.Query))
	})
	return _c
}

func (_c *OrgPATsService_Search_Call) Return(_a0 orgpats.OrganizationPATs, _a1 error) *OrgPATsService_Search_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *OrgPATsService_Search_Call) RunAndReturn(run func(context.Context, string, *rql.Query) (orgpats.OrganizationPATs, error)) *OrgPATsService_Search_Call {
	_c.Call.Return(run)
	return _c
}

// NewOrgPATsService creates a new instance of OrgPATsService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOrgPATsService(t interface {
	mock.TestingT
	Cleanup(func())
}) *OrgPATsService {
	mock := &OrgPATsService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
