// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	models "github.com/raystack/frontier/core/userpat/models"
	mock "github.com/stretchr/testify/mock"

	rql "github.com/raystack/salt/rql"

	time "time"

	userpat "github.com/raystack/frontier/core/userpat"
)

// UserPATService is an autogenerated mock type for the UserPATService type
type UserPATService struct {
	mock.Mock
}

type UserPATService_Expecter struct {
	mock *mock.Mock
}

func (_m *UserPATService) EXPECT() *UserPATService_Expecter {
	return &UserPATService_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, req
func (_m *UserPATService) Create(ctx context.Context, req userpat.CreateRequest) (models.PAT, string, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 models.PAT
	var r1 string
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, userpat.CreateRequest) (models.PAT, string, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, userpat.CreateRequest) models.PAT); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Get(0).(models.PAT)
	}

	if rf, ok := ret.Get(1).(func(context.Context, userpat.CreateRequest) string); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Get(1).(string)
	}

	if rf, ok := ret.Get(2).(func(context.Context, userpat.CreateRequest) error); ok {
		r2 = rf(ctx, req)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// UserPATService_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type UserPATService_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - req userpat.CreateRequest
func (_e *UserPATService_Expecter) Create(ctx interface{}, req interface{}) *UserPATService_Create_Call {
	return &UserPATService_Create_Call{Call: _e.mock.On("Create", ctx, req)}
}

func (_c *UserPATService_Create_Call) Run(run func(ctx context.Context, req userpat.CreateRequest)) *UserPATService_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(userpat.CreateRequest))
	})
	return _c
}

func (_c *UserPATService_Create_Call) Return(_a0 models.PAT, _a1 string, _a2 error) *UserPATService_Create_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *UserPATService_Create_Call) RunAndReturn(run func(context.Context, userpat.CreateRequest) (models.PAT, string, error)) *UserPATService_Create_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, userID, orgID, query
func (_m *UserPATService) List(ctx context.Context, userID string, orgID string, query *rql.Query) (models.PATList, error) {
	ret := _m.Called(ctx, userID, orgID, query)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 models.PATList
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, *rql.Query) (models.PATList, error)); ok {
		return rf(ctx, userID, orgID, query)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, *rql.Query) models.PATList); ok {
		r0 = rf(ctx, userID, orgID, query)
	} else {
		r0 = ret.Get(0).(models.PATList)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, *rql.Query) error); ok {
		r1 = rf(ctx, userID, orgID, query)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserPATService_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type UserPATService_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - orgID string
//   - query *rql.Query
func (_e *UserPATService_Expecter) List(ctx interface{}, userID interface{}, orgID interface{}, query interface{}) *UserPATService_List_Call {
	return &UserPATService_List_Call{Call: _e.mock.On("List", ctx, userID, orgID, query)}
}

func (_c *UserPATService_List_Call) Run(run func(ctx context.Context, userID string, orgID string, query *rql.Query)) *UserPATService_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(*rql.Query))
	})
	return _c
}

func (_c *UserPATService_List_Call) Return(_a0 models.PATList, _a1 error) *UserPATService_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UserPATService_List_Call) RunAndReturn(run func(context.Context, string, string, *rql.Query) (models.PATList, error)) *UserPATService_List_Call {
	_c.Call.Return(run)
	return _c
}

// ValidateExpiry provides a mock function with given fields: expiresAt
func (_m *UserPATService) ValidateExpiry(expiresAt time.Time) error {
	ret := _m.Called(expiresAt)

	if len(ret) == 0 {
		panic("no return value specified for ValidateExpiry")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(time.Time) error); ok {
		r0 = rf(expiresAt)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UserPATService_ValidateExpiry_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateExpiry'
type UserPATService_ValidateExpiry_Call struct {
	*mock.Call
}

// ValidateExpiry is a helper method to define mock.On call
//   - expiresAt time.Time
func (_e *UserPATService_Expecter) ValidateExpiry(expiresAt interface{}) *UserPATService_ValidateExpiry_Call {
	return &UserPATService_ValidateExpiry_Call{Call: _e.mock.On("ValidateExpiry", expiresAt)}
}

func (_c *UserPATService_ValidateExpiry_Call) Run(run func(expiresAt time.Time)) *UserPATService_ValidateExpiry_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(time.Time))
	})
	return _c
}

func (_c *UserPATService_ValidateExpiry_Call) Return(_a0 error) *UserPATService_ValidateExpiry_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *UserPATService_ValidateExpiry_Call) RunAndReturn(run func(time.Time) error) *UserPATService_ValidateExpiry_Call {
	_c.Call.Return(run)
	return _c
}

// NewUserPATService creates a new instance of UserPATService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserPATService(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserPATService {
	mock := &UserPATService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
