// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	policy "github.com/raystack/frontier/core/policy"
	mock "github.com/stretchr/testify/mock"
)

// PolicyService is an autogenerated mock type for the PolicyService type
type PolicyService struct {
	mock.Mock
}

type PolicyService_Expecter struct {
	mock *mock.Mock
}

func (_m *PolicyService) EXPECT() *PolicyService_Expecter {
	return &PolicyService_Expecter{mock: &_m.Mock}
}

// ProjectMemberCount provides a mock function with given fields: ctx, ids
func (_m *PolicyService) ProjectMemberCount(ctx context.Context, ids []string) ([]policy.MemberCount, error) {
	ret := _m.Called(ctx, ids)

	if len(ret) == 0 {
		panic("no return value specified for ProjectMemberCount")
	}

	var r0 []policy.MemberCount
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []string) ([]policy.MemberCount, error)); ok {
		return rf(ctx, ids)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []string) []policy.MemberCount); ok {
		r0 = rf(ctx, ids)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]policy.MemberCount)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []string) error); ok {
		r1 = rf(ctx, ids)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PolicyService_ProjectMemberCount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ProjectMemberCount'
type PolicyService_ProjectMemberCount_Call struct {
	*mock.Call
}

// ProjectMemberCount is a helper method to define mock.On call
//   - ctx context.Context
//   - ids []string
func (_e *PolicyService_Expecter) ProjectMemberCount(ctx interface{}, ids interface{}) *PolicyService_ProjectMemberCount_Call {
	return &PolicyService_ProjectMemberCount_Call{Call: _e.mock.On("ProjectMemberCount", ctx, ids)}
}

func (_c *PolicyService_ProjectMemberCount_Call) Run(run func(ctx context.Context, ids []string)) *PolicyService_ProjectMemberCount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]string))
	})
	return _c
}

func (_c *PolicyService_ProjectMemberCount_Call) Return(_a0 []policy.MemberCount, _a1 error) *PolicyService_ProjectMemberCount_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *PolicyService_ProjectMemberCount_Call) RunAndReturn(run func(context.Context, []string) ([]policy.MemberCount, error)) *PolicyService_ProjectMemberCount_Call {
	_c.Call.Return(run)
	return _c
}

// NewPolicyService creates a new instance of PolicyService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPolicyService(t interface {
	mock.TestingT
	Cleanup(func())
}) *PolicyService {
	mock := &PolicyService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
