project_name: shield

release:
  prerelease: auto

before:
  hooks:
    - make test

builds:
  - id: "shield"
    goos: [linux, darwin, windows]
    goarch: [amd64, arm, arm64]
    binary: shield
    main: ./main.go
    ldflags:
      - -s -w -X github.com/raystack/shield/config.Version={{.Tag}}
      - -X github.com/raystack/shield/config.BuildCommit={{.FullCommit}}
      - -X github.com/raystack/shield/config.BuildDate={{.Date}}
    env:
      - CGO_ENABLED=0

archives:
  - id: "shield-archive"
    format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs"
      - "^test"
      - "^build"
      - "^chore"

checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ .Tag }}-next"

dockers:
  - goos: linux
    goarch: amd64
    ids:
      - shield
    dockerfile: Dockerfile
    image_templates:
      - "docker.io/raystack/{{.ProjectName}}:latest"
      - "docker.io/raystack/{{.ProjectName}}:{{ .Version }}"
      - "docker.io/raystack/{{.ProjectName}}:{{ .Tag }}-amd64"

nfpms:
  - maintainer: Raystack
    description: Identity and authorization system
    homepage: https://github.com/raystack/shield
    license: Apache 2.0
    formats:
      - deb
      - rpm

scoops:
  - homepage: "https://github.com/raystack/shield"
    description: "Identity and authorization system"
    license: Apache 2.0
    bucket:
      owner: raystack
      name: scoop-bucket

brews:
  - name: shield
    homepage: "https://github.com/raystack/shield"
    description: "Identity and authorization system"
    tap:
      owner: raystack
      name: homebrew-tap
    license: "Apache 2.0"
    folder: Formula
    dependencies:
      - name: git
    install: |-
      bin.install "shield"
    commit_author:
      name: Ravi Suhag
      email: suhag.ravi@gmail.com
