FROM 1.18-alpine3.15 as builder

RUN apk add make

WORKDIR /go/src/app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN make build

FROM alpine:3.15
COPY --from=builder /go/src/app/shield /usr/local/bin/
ENTRYPOINT [ "shield" ]