# Build the UI
FROM node:18-alpine3.18 as ui-builder
RUN apk add --no-cache make
WORKDIR /app

COPY ui ./ui
COPY Makefile .
RUN make ui

# Build the Go binary
FROM golang:1.22.2-alpine3.18 as builder
RUN apk add --no-cache make
WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .
COPY --from=ui-builder /app/ui/dist /app/ui/dist

RUN make build

# Build the final image
FROM alpine:3.18
COPY --from=builder /app/frontier /usr/bin/
RUN apk update && \
    apk add --no-cache ca-certificates libc6-compat && \
    rm -rf /var/cache/apk/*

ENTRYPOINT ["frontier"]