// Code generated by mockery v2.10.0. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// Policy is an autogenerated mock type for the Policy type
type Policy struct {
	mock.Mock
}

// AddPolicy provides a mock function with given fields: ctx, schema
func (_m *Policy) AddPolicy(ctx context.Context, schema string) error {
	ret := _m.Called(ctx, schema)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, schema)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
