// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	userpat "github.com/raystack/frontier/core/userpat"
	mock "github.com/stretchr/testify/mock"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

type Repository_Expecter struct {
	mock *mock.Mock
}

func (_m *Repository) EXPECT() *Repository_Expecter {
	return &Repository_Expecter{mock: &_m.Mock}
}

// CountActive provides a mock function with given fields: ctx, userID, orgID
func (_m *Repository) CountActive(ctx context.Context, userID string, orgID string) (int64, error) {
	ret := _m.Called(ctx, userID, orgID)

	if len(ret) == 0 {
		panic("no return value specified for CountActive")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (int64, error)); ok {
		return rf(ctx, userID, orgID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) int64); ok {
		r0 = rf(ctx, userID, orgID)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, userID, orgID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Repository_CountActive_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountActive'
type Repository_CountActive_Call struct {
	*mock.Call
}

// CountActive is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - orgID string
func (_e *Repository_Expecter) CountActive(ctx interface{}, userID interface{}, orgID interface{}) *Repository_CountActive_Call {
	return &Repository_CountActive_Call{Call: _e.mock.On("CountActive", ctx, userID, orgID)}
}

func (_c *Repository_CountActive_Call) Run(run func(ctx context.Context, userID string, orgID string)) *Repository_CountActive_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *Repository_CountActive_Call) Return(_a0 int64, _a1 error) *Repository_CountActive_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Repository_CountActive_Call) RunAndReturn(run func(context.Context, string, string) (int64, error)) *Repository_CountActive_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function with given fields: ctx, pat
func (_m *Repository) Create(ctx context.Context, pat userpat.PersonalAccessToken) (userpat.PersonalAccessToken, error) {
	ret := _m.Called(ctx, pat)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 userpat.PersonalAccessToken
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, userpat.PersonalAccessToken) (userpat.PersonalAccessToken, error)); ok {
		return rf(ctx, pat)
	}
	if rf, ok := ret.Get(0).(func(context.Context, userpat.PersonalAccessToken) userpat.PersonalAccessToken); ok {
		r0 = rf(ctx, pat)
	} else {
		r0 = ret.Get(0).(userpat.PersonalAccessToken)
	}

	if rf, ok := ret.Get(1).(func(context.Context, userpat.PersonalAccessToken) error); ok {
		r1 = rf(ctx, pat)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Repository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type Repository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - pat userpat.PersonalAccessToken
func (_e *Repository_Expecter) Create(ctx interface{}, pat interface{}) *Repository_Create_Call {
	return &Repository_Create_Call{Call: _e.mock.On("Create", ctx, pat)}
}

func (_c *Repository_Create_Call) Run(run func(ctx context.Context, pat userpat.PersonalAccessToken)) *Repository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(userpat.PersonalAccessToken))
	})
	return _c
}

func (_c *Repository_Create_Call) Return(_a0 userpat.PersonalAccessToken, _a1 error) *Repository_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Repository_Create_Call) RunAndReturn(run func(context.Context, userpat.PersonalAccessToken) (userpat.PersonalAccessToken, error)) *Repository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// NewRepository creates a new instance of Repository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *Repository {
	mock := &Repository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
