// Code generated by mockery v2.45.0. DO NOT EDIT.

package mocks

import (
	context "context"

	role "github.com/raystack/frontier/core/role"
	mock "github.com/stretchr/testify/mock"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

type Repository_Expecter struct {
	mock *mock.Mock
}

func (_m *Repository) EXPECT() *Repository_Expecter {
	return &Repository_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function with given fields: ctx, roleID
func (_m *Repository) Delete(ctx context.Context, roleID string) error {
	ret := _m.Called(ctx, roleID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, roleID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Repository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type Repository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - roleID string
func (_e *Repository_Expecter) Delete(ctx interface{}, roleID interface{}) *Repository_Delete_Call {
	return &Repository_Delete_Call{Call: _e.mock.On("Delete", ctx, roleID)}
}

func (_c *Repository_Delete_Call) Run(run func(ctx context.Context, roleID string)) *Repository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *Repository_Delete_Call) Return(_a0 error) *Repository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Repository_Delete_Call) RunAndReturn(run func(context.Context, string) error) *Repository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: ctx, id
func (_m *Repository) Get(ctx context.Context, id string) (role.Role, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 role.Role
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (role.Role, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) role.Role); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(role.Role)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Repository_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type Repository_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *Repository_Expecter) Get(ctx interface{}, id interface{}) *Repository_Get_Call {
	return &Repository_Get_Call{Call: _e.mock.On("Get", ctx, id)}
}

func (_c *Repository_Get_Call) Run(run func(ctx context.Context, id string)) *Repository_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *Repository_Get_Call) Return(_a0 role.Role, _a1 error) *Repository_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Repository_Get_Call) RunAndReturn(run func(context.Context, string) (role.Role, error)) *Repository_Get_Call {
	_c.Call.Return(run)
	return _c
}

// GetByName provides a mock function with given fields: ctx, orgID, name
func (_m *Repository) GetByName(ctx context.Context, orgID string, name string) (role.Role, error) {
	ret := _m.Called(ctx, orgID, name)

	if len(ret) == 0 {
		panic("no return value specified for GetByName")
	}

	var r0 role.Role
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (role.Role, error)); ok {
		return rf(ctx, orgID, name)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) role.Role); ok {
		r0 = rf(ctx, orgID, name)
	} else {
		r0 = ret.Get(0).(role.Role)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, orgID, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Repository_GetByName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByName'
type Repository_GetByName_Call struct {
	*mock.Call
}

// GetByName is a helper method to define mock.On call
//   - ctx context.Context
//   - orgID string
//   - name string
func (_e *Repository_Expecter) GetByName(ctx interface{}, orgID interface{}, name interface{}) *Repository_GetByName_Call {
	return &Repository_GetByName_Call{Call: _e.mock.On("GetByName", ctx, orgID, name)}
}

func (_c *Repository_GetByName_Call) Run(run func(ctx context.Context, orgID string, name string)) *Repository_GetByName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *Repository_GetByName_Call) Return(_a0 role.Role, _a1 error) *Repository_GetByName_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Repository_GetByName_Call) RunAndReturn(run func(context.Context, string, string) (role.Role, error)) *Repository_GetByName_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, f
func (_m *Repository) List(ctx context.Context, f role.Filter) ([]role.Role, error) {
	ret := _m.Called(ctx, f)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []role.Role
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, role.Filter) ([]role.Role, error)); ok {
		return rf(ctx, f)
	}
	if rf, ok := ret.Get(0).(func(context.Context, role.Filter) []role.Role); ok {
		r0 = rf(ctx, f)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]role.Role)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, role.Filter) error); ok {
		r1 = rf(ctx, f)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Repository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type Repository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - f role.Filter
func (_e *Repository_Expecter) List(ctx interface{}, f interface{}) *Repository_List_Call {
	return &Repository_List_Call{Call: _e.mock.On("List", ctx, f)}
}

func (_c *Repository_List_Call) Run(run func(ctx context.Context, f role.Filter)) *Repository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(role.Filter))
	})
	return _c
}

func (_c *Repository_List_Call) Return(_a0 []role.Role, _a1 error) *Repository_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Repository_List_Call) RunAndReturn(run func(context.Context, role.Filter) ([]role.Role, error)) *Repository_List_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, toUpdate
func (_m *Repository) Update(ctx context.Context, toUpdate role.Role) (role.Role, error) {
	ret := _m.Called(ctx, toUpdate)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 role.Role
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, role.Role) (role.Role, error)); ok {
		return rf(ctx, toUpdate)
	}
	if rf, ok := ret.Get(0).(func(context.Context, role.Role) role.Role); ok {
		r0 = rf(ctx, toUpdate)
	} else {
		r0 = ret.Get(0).(role.Role)
	}

	if rf, ok := ret.Get(1).(func(context.Context, role.Role) error); ok {
		r1 = rf(ctx, toUpdate)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Repository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type Repository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - toUpdate role.Role
func (_e *Repository_Expecter) Update(ctx interface{}, toUpdate interface{}) *Repository_Update_Call {
	return &Repository_Update_Call{Call: _e.mock.On("Update", ctx, toUpdate)}
}

func (_c *Repository_Update_Call) Run(run func(ctx context.Context, toUpdate role.Role)) *Repository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(role.Role))
	})
	return _c
}

func (_c *Repository_Update_Call) Return(_a0 role.Role, _a1 error) *Repository_Update_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Repository_Update_Call) RunAndReturn(run func(context.Context, role.Role) (role.Role, error)) *Repository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// Upsert provides a mock function with given fields: ctx, _a1
func (_m *Repository) Upsert(ctx context.Context, _a1 role.Role) (role.Role, error) {
	ret := _m.Called(ctx, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Upsert")
	}

	var r0 role.Role
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, role.Role) (role.Role, error)); ok {
		return rf(ctx, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, role.Role) role.Role); ok {
		r0 = rf(ctx, _a1)
	} else {
		r0 = ret.Get(0).(role.Role)
	}

	if rf, ok := ret.Get(1).(func(context.Context, role.Role) error); ok {
		r1 = rf(ctx, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Repository_Upsert_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Upsert'
type Repository_Upsert_Call struct {
	*mock.Call
}

// Upsert is a helper method to define mock.On call
//   - ctx context.Context
//   - _a1 role.Role
func (_e *Repository_Expecter) Upsert(ctx interface{}, _a1 interface{}) *Repository_Upsert_Call {
	return &Repository_Upsert_Call{Call: _e.mock.On("Upsert", ctx, _a1)}
}

func (_c *Repository_Upsert_Call) Run(run func(ctx context.Context, _a1 role.Role)) *Repository_Upsert_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(role.Role))
	})
	return _c
}

func (_c *Repository_Upsert_Call) Return(_a0 role.Role, _a1 error) *Repository_Upsert_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Repository_Upsert_Call) RunAndReturn(run func(context.Context, role.Role) (role.Role, error)) *Repository_Upsert_Call {
	_c.Call.Return(run)
	return _c
}

// NewRepository creates a new instance of Repository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *Repository {
	mock := &Repository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
