package v1beta1connect

import (
	"github.com/raystack/frontier/pkg/errors"
)

var (
	ErrBadRequest              = errors.New("invalid syntax in body")
	ErrInvalidMetadata         = errors.New("metadata schema validation failed")
	ErrOperationUnsupported    = errors.New("operation not supported")
	ErrInternalServerError     = errors.New("internal server error")
	ErrUnauthenticated         = errors.New("not authenticated")
	ErrUnauthorized            = errors.New("not authorized")
	ErrNotFound                = errors.New("not found")
	ErrInvalidEmail            = errors.New("Invalid email")
	ErrUserNotExist            = errors.New("user doesn't exist")
	ErrInvalidNamesapceOrID    = errors.New("namespace and ID cannot be empty")
	ErrConflictRequest         = errors.New("already exist")
	ErrBadBodyMetaSchemaError  = errors.New(ErrBadRequest.Error() + " : " + ErrInvalidMetadata.Error())
	ErrInvalidActorType        = errors.New("invalid actor type")
	ErrActivityRequired        = errors.New("activity is required")
	ErrStatusRequired          = errors.New("status is required")
	ErrProspectIdRequired      = errors.New("prospect ID is required")
	ErrProspectNotFound        = errors.New("record not found for the given input")
	ErrRQLParse                = errors.New("error parsing RQL query")
	ErrOrgDisabled             = errors.New("org is disabled. Please contact your administrator to enable it")
	ErrRoleFilter              = errors.New("cannot use role filters and with_roles together")
	ErrMinAdminCount           = errors.New("org must have at least one admin, consider adding another admin before removing")
	ErrDomainNotFound          = errors.New("domain whitelist request doesn't exist")
	ErrDomainAlreadyExists     = errors.New("domain name already exists for that organization")
	ErrInvalidHost             = errors.New("invalid domain, no such host found")
	ErrTXTRecordNotFound       = errors.New("required TXT record not found for domain verification")
	ErrDomainMismatch          = errors.New("user and org's whitelisted domains doesn't match")
	ErrInvitationNotFound      = errors.New("invitation not found")
	ErrInvitationExpired       = errors.New("invitation expired")
	ErrAlreadyMember           = errors.New("user is already a member of the organization")
	ErrEmptyEmailID            = errors.New("email id is empty")
	ErrEmailConflict           = errors.New("user email can't be updated")
	ErrCustomerNotFound        = errors.New("customer doesn't exist")
	ErrServiceUserNotFound     = errors.New("service user not found")
	ErrServiceUserCredNotFound = errors.New("service user credentials not found")
)
