// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	customer "github.com/raystack/frontier/billing/customer"

	mock "github.com/stretchr/testify/mock"
)

// CustomerRepository is an autogenerated mock type for the CustomerRepository type
type CustomerRepository struct {
	mock.Mock
}

type CustomerRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *CustomerRepository) EXPECT() *CustomerRepository_Expecter {
	return &CustomerRepository_Expecter{mock: &_m.Mock}
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *CustomerRepository) GetByID(ctx context.Context, id string) (customer.Customer, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 customer.Customer
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (customer.Customer, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) customer.Customer); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(customer.Customer)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CustomerRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type CustomerRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *CustomerRepository_Expecter) GetByID(ctx interface{}, id interface{}) *CustomerRepository_GetByID_Call {
	return &CustomerRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *CustomerRepository_GetByID_Call) Run(run func(ctx context.Context, id string)) *CustomerRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *CustomerRepository_GetByID_Call) Return(_a0 customer.Customer, _a1 error) *CustomerRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *CustomerRepository_GetByID_Call) RunAndReturn(run func(context.Context, string) (customer.Customer, error)) *CustomerRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// NewCustomerRepository creates a new instance of CustomerRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCustomerRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *CustomerRepository {
	mock := &CustomerRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
