// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	authenticate "github.com/raystack/frontier/core/authenticate"

	mock "github.com/stretchr/testify/mock"
)

// MembershipService is an autogenerated mock type for the MembershipService type
type MembershipService struct {
	mock.Mock
}

type MembershipService_Expecter struct {
	mock *mock.Mock
}

func (_m *MembershipService) EXPECT() *MembershipService_Expecter {
	return &MembershipService_Expecter{mock: &_m.Mock}
}

// ListGroupsByPrincipal provides a mock function with given fields: ctx, principal, orgID
func (_m *MembershipService) ListGroupsByPrincipal(ctx context.Context, principal authenticate.Principal, orgID string) ([]string, error) {
	ret := _m.Called(ctx, principal, orgID)

	if len(ret) == 0 {
		panic("no return value specified for ListGroupsByPrincipal")
	}

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, authenticate.Principal, string) ([]string, error)); ok {
		return rf(ctx, principal, orgID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, authenticate.Principal, string) []string); ok {
		r0 = rf(ctx, principal, orgID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, authenticate.Principal, string) error); ok {
		r1 = rf(ctx, principal, orgID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MembershipService_ListGroupsByPrincipal_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListGroupsByPrincipal'
type MembershipService_ListGroupsByPrincipal_Call struct {
	*mock.Call
}

// ListGroupsByPrincipal is a helper method to define mock.On call
//   - ctx context.Context
//   - principal authenticate.Principal
//   - orgID string
func (_e *MembershipService_Expecter) ListGroupsByPrincipal(ctx interface{}, principal interface{}, orgID interface{}) *MembershipService_ListGroupsByPrincipal_Call {
	return &MembershipService_ListGroupsByPrincipal_Call{Call: _e.mock.On("ListGroupsByPrincipal", ctx, principal, orgID)}
}

func (_c *MembershipService_ListGroupsByPrincipal_Call) Run(run func(ctx context.Context, principal authenticate.Principal, orgID string)) *MembershipService_ListGroupsByPrincipal_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(authenticate.Principal), args[2].(string))
	})
	return _c
}

func (_c *MembershipService_ListGroupsByPrincipal_Call) Return(_a0 []string, _a1 error) *MembershipService_ListGroupsByPrincipal_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MembershipService_ListGroupsByPrincipal_Call) RunAndReturn(run func(context.Context, authenticate.Principal, string) ([]string, error)) *MembershipService_ListGroupsByPrincipal_Call {
	_c.Call.Return(run)
	return _c
}

// OnGroupCreated provides a mock function with given fields: ctx, groupID, orgID, creatorID, creatorType
func (_m *MembershipService) OnGroupCreated(ctx context.Context, groupID string, orgID string, creatorID string, creatorType string) error {
	ret := _m.Called(ctx, groupID, orgID, creatorID, creatorType)

	if len(ret) == 0 {
		panic("no return value specified for OnGroupCreated")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string) error); ok {
		r0 = rf(ctx, groupID, orgID, creatorID, creatorType)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MembershipService_OnGroupCreated_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OnGroupCreated'
type MembershipService_OnGroupCreated_Call struct {
	*mock.Call
}

// OnGroupCreated is a helper method to define mock.On call
//   - ctx context.Context
//   - groupID string
//   - orgID string
//   - creatorID string
//   - creatorType string
func (_e *MembershipService_Expecter) OnGroupCreated(ctx interface{}, groupID interface{}, orgID interface{}, creatorID interface{}, creatorType interface{}) *MembershipService_OnGroupCreated_Call {
	return &MembershipService_OnGroupCreated_Call{Call: _e.mock.On("OnGroupCreated", ctx, groupID, orgID, creatorID, creatorType)}
}

func (_c *MembershipService_OnGroupCreated_Call) Run(run func(ctx context.Context, groupID string, orgID string, creatorID string, creatorType string)) *MembershipService_OnGroupCreated_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string), args[4].(string))
	})
	return _c
}

func (_c *MembershipService_OnGroupCreated_Call) Return(_a0 error) *MembershipService_OnGroupCreated_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MembershipService_OnGroupCreated_Call) RunAndReturn(run func(context.Context, string, string, string, string) error) *MembershipService_OnGroupCreated_Call {
	_c.Call.Return(run)
	return _c
}

// NewMembershipService creates a new instance of MembershipService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMembershipService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MembershipService {
	mock := &MembershipService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
