// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	sqlx "github.com/jmoiron/sqlx"

	consent "github.com/raystack/frontier/core/consent"
	mock "github.com/stretchr/testify/mock"
)

// ConsentService is an autogenerated mock type for the ConsentService type
type ConsentService struct {
	mock.Mock
}

type ConsentService_Expecter struct {
	mock *mock.Mock
}

func (_m *ConsentService) EXPECT() *ConsentService_Expecter {
	return &ConsentService_Expecter{mock: &_m.Mock}
}

// Grant provides a mock function with given fields: ctx, tx, req
func (_m *ConsentService) Grant(ctx context.Context, tx *sqlx.Tx, req consent.GrantRequest) (consent.Consent, error) {
	ret := _m.Called(ctx, tx, req)

	if len(ret) == 0 {
		panic("no return value specified for Grant")
	}

	var r0 consent.Consent
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *sqlx.Tx, consent.GrantRequest) (consent.Consent, error)); ok {
		return rf(ctx, tx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *sqlx.Tx, consent.GrantRequest) consent.Consent); ok {
		r0 = rf(ctx, tx, req)
	} else {
		r0 = ret.Get(0).(consent.Consent)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *sqlx.Tx, consent.GrantRequest) error); ok {
		r1 = rf(ctx, tx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ConsentService_Grant_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Grant'
type ConsentService_Grant_Call struct {
	*mock.Call
}

// Grant is a helper method to define mock.On call
//   - ctx context.Context
//   - tx *sqlx.Tx
//   - req consent.GrantRequest
func (_e *ConsentService_Expecter) Grant(ctx interface{}, tx interface{}, req interface{}) *ConsentService_Grant_Call {
	return &ConsentService_Grant_Call{Call: _e.mock.On("Grant", ctx, tx, req)}
}

func (_c *ConsentService_Grant_Call) Run(run func(ctx context.Context, tx *sqlx.Tx, req consent.GrantRequest)) *ConsentService_Grant_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*sqlx.Tx), args[2].(consent.GrantRequest))
	})
	return _c
}

func (_c *ConsentService_Grant_Call) Return(_a0 consent.Consent, _a1 error) *ConsentService_Grant_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ConsentService_Grant_Call) RunAndReturn(run func(context.Context, *sqlx.Tx, consent.GrantRequest) (consent.Consent, error)) *ConsentService_Grant_Call {
	_c.Call.Return(run)
	return _c
}

// RecordGranted provides a mock function with given fields: ctx, granted
func (_m *ConsentService) RecordGranted(ctx context.Context, granted consent.Consent) {
	_m.Called(ctx, granted)
}

// ConsentService_RecordGranted_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RecordGranted'
type ConsentService_RecordGranted_Call struct {
	*mock.Call
}

// RecordGranted is a helper method to define mock.On call
//   - ctx context.Context
//   - granted consent.Consent
func (_e *ConsentService_Expecter) RecordGranted(ctx interface{}, granted interface{}) *ConsentService_RecordGranted_Call {
	return &ConsentService_RecordGranted_Call{Call: _e.mock.On("RecordGranted", ctx, granted)}
}

func (_c *ConsentService_RecordGranted_Call) Run(run func(ctx context.Context, granted consent.Consent)) *ConsentService_RecordGranted_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(consent.Consent))
	})
	return _c
}

func (_c *ConsentService_RecordGranted_Call) Return() *ConsentService_RecordGranted_Call {
	_c.Call.Return()
	return _c
}

func (_c *ConsentService_RecordGranted_Call) RunAndReturn(run func(context.Context, consent.Consent)) *ConsentService_RecordGranted_Call {
	_c.Run(run)
	return _c
}

// ResolveAll provides a mock function with given fields: ids
func (_m *ConsentService) ResolveAll(ids []string) ([]consent.Document, error) {
	ret := _m.Called(ids)

	if len(ret) == 0 {
		panic("no return value specified for ResolveAll")
	}

	var r0 []consent.Document
	var r1 error
	if rf, ok := ret.Get(0).(func([]string) ([]consent.Document, error)); ok {
		return rf(ids)
	}
	if rf, ok := ret.Get(0).(func([]string) []consent.Document); ok {
		r0 = rf(ids)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]consent.Document)
		}
	}

	if rf, ok := ret.Get(1).(func([]string) error); ok {
		r1 = rf(ids)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ConsentService_ResolveAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ResolveAll'
type ConsentService_ResolveAll_Call struct {
	*mock.Call
}

// ResolveAll is a helper method to define mock.On call
//   - ids []string
func (_e *ConsentService_Expecter) ResolveAll(ids interface{}) *ConsentService_ResolveAll_Call {
	return &ConsentService_ResolveAll_Call{Call: _e.mock.On("ResolveAll", ids)}
}

func (_c *ConsentService_ResolveAll_Call) Run(run func(ids []string)) *ConsentService_ResolveAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]string))
	})
	return _c
}

func (_c *ConsentService_ResolveAll_Call) Return(_a0 []consent.Document, _a1 error) *ConsentService_ResolveAll_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ConsentService_ResolveAll_Call) RunAndReturn(run func([]string) ([]consent.Document, error)) *ConsentService_ResolveAll_Call {
	_c.Call.Return(run)
	return _c
}

// NewConsentService creates a new instance of ConsentService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewConsentService(t interface {
	mock.TestingT
	Cleanup(func())
}) *ConsentService {
	mock := &ConsentService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
