// Code generated by mockery v2.10.0. DO NOT EDIT.

package mocks

import (
	http "net/http"

	structs "github.com/odpf/shield/structs"
	mock "github.com/stretchr/testify/mock"
)

// RuleMatcher is an autogenerated mock type for the RuleMatcher type
type RuleMatcher struct {
	mock.Mock
}

// Match provides a mock function with given fields: req
func (_m *RuleMatcher) Match(req *http.Request) (*structs.Rule, error) {
	ret := _m.Called(req)

	var r0 *structs.Rule
	if rf, ok := ret.Get(0).(func(*http.Request) *structs.Rule); ok {
		r0 = rf(req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*structs.Rule)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*http.Request) error); ok {
		r1 = rf(req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
