// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// CheckoutService is an autogenerated mock type for the CheckoutService type
type CheckoutService struct {
	mock.Mock
}

type CheckoutService_Expecter struct {
	mock *mock.Mock
}

func (_m *CheckoutService) EXPECT() *CheckoutService_Expecter {
	return &CheckoutService_Expecter{mock: &_m.Mock}
}

// DeleteByCustomer provides a mock function with given fields: ctx, customerID
func (_m *CheckoutService) DeleteByCustomer(ctx context.Context, customerID string) error {
	ret := _m.Called(ctx, customerID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteByCustomer")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, customerID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CheckoutService_DeleteByCustomer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteByCustomer'
type CheckoutService_DeleteByCustomer_Call struct {
	*mock.Call
}

// DeleteByCustomer is a helper method to define mock.On call
//   - ctx context.Context
//   - customerID string
func (_e *CheckoutService_Expecter) DeleteByCustomer(ctx interface{}, customerID interface{}) *CheckoutService_DeleteByCustomer_Call {
	return &CheckoutService_DeleteByCustomer_Call{Call: _e.mock.On("DeleteByCustomer", ctx, customerID)}
}

func (_c *CheckoutService_DeleteByCustomer_Call) Run(run func(ctx context.Context, customerID string)) *CheckoutService_DeleteByCustomer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *CheckoutService_DeleteByCustomer_Call) Return(_a0 error) *CheckoutService_DeleteByCustomer_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *CheckoutService_DeleteByCustomer_Call) RunAndReturn(run func(context.Context, string) error) *CheckoutService_DeleteByCustomer_Call {
	_c.Call.Return(run)
	return _c
}

// NewCheckoutService creates a new instance of CheckoutService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCheckoutService(t interface {
	mock.TestingT
	Cleanup(func())
}) *CheckoutService {
	mock := &CheckoutService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
