// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// CreditService is an autogenerated mock type for the CreditService type
type CreditService struct {
	mock.Mock
}

type CreditService_Expecter struct {
	mock *mock.Mock
}

func (_m *CreditService) EXPECT() *CreditService_Expecter {
	return &CreditService_Expecter{mock: &_m.Mock}
}

// DeleteByAccountID provides a mock function with given fields: ctx, accountID
func (_m *CreditService) DeleteByAccountID(ctx context.Context, accountID string) error {
	ret := _m.Called(ctx, accountID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteByAccountID")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, accountID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreditService_DeleteByAccountID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteByAccountID'
type CreditService_DeleteByAccountID_Call struct {
	*mock.Call
}

// DeleteByAccountID is a helper method to define mock.On call
//   - ctx context.Context
//   - accountID string
func (_e *CreditService_Expecter) DeleteByAccountID(ctx interface{}, accountID interface{}) *CreditService_DeleteByAccountID_Call {
	return &CreditService_DeleteByAccountID_Call{Call: _e.mock.On("DeleteByAccountID", ctx, accountID)}
}

func (_c *CreditService_DeleteByAccountID_Call) Run(run func(ctx context.Context, accountID string)) *CreditService_DeleteByAccountID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *CreditService_DeleteByAccountID_Call) Return(_a0 error) *CreditService_DeleteByAccountID_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *CreditService_DeleteByAccountID_Call) RunAndReturn(run func(context.Context, string) error) *CreditService_DeleteByAccountID_Call {
	_c.Call.Return(run)
	return _c
}

// GetBalance provides a mock function with given fields: ctx, accountID
func (_m *CreditService) GetBalance(ctx context.Context, accountID string) (int64, error) {
	ret := _m.Called(ctx, accountID)

	if len(ret) == 0 {
		panic("no return value specified for GetBalance")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (int64, error)); ok {
		return rf(ctx, accountID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) int64); ok {
		r0 = rf(ctx, accountID)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, accountID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreditService_GetBalance_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBalance'
type CreditService_GetBalance_Call struct {
	*mock.Call
}

// GetBalance is a helper method to define mock.On call
//   - ctx context.Context
//   - accountID string
func (_e *CreditService_Expecter) GetBalance(ctx interface{}, accountID interface{}) *CreditService_GetBalance_Call {
	return &CreditService_GetBalance_Call{Call: _e.mock.On("GetBalance", ctx, accountID)}
}

func (_c *CreditService_GetBalance_Call) Run(run func(ctx context.Context, accountID string)) *CreditService_GetBalance_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *CreditService_GetBalance_Call) Return(_a0 int64, _a1 error) *CreditService_GetBalance_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *CreditService_GetBalance_Call) RunAndReturn(run func(context.Context, string) (int64, error)) *CreditService_GetBalance_Call {
	_c.Call.Return(run)
	return _c
}

// NewCreditService creates a new instance of CreditService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCreditService(t interface {
	mock.TestingT
	Cleanup(func())
}) *CreditService {
	mock := &CreditService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
