// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	customer "github.com/raystack/frontier/billing/customer"

	invoice "github.com/raystack/frontier/billing/invoice"

	mock "github.com/stretchr/testify/mock"
)

// InvoiceService is an autogenerated mock type for the InvoiceService type
type InvoiceService struct {
	mock.Mock
}

type InvoiceService_Expecter struct {
	mock *mock.Mock
}

func (_m *InvoiceService) EXPECT() *InvoiceService_Expecter {
	return &InvoiceService_Expecter{mock: &_m.Mock}
}

// DeleteByCustomer provides a mock function with given fields: ctx, customr
func (_m *InvoiceService) DeleteByCustomer(ctx context.Context, customr customer.Customer) error {
	ret := _m.Called(ctx, customr)

	if len(ret) == 0 {
		panic("no return value specified for DeleteByCustomer")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, customer.Customer) error); ok {
		r0 = rf(ctx, customr)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// InvoiceService_DeleteByCustomer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteByCustomer'
type InvoiceService_DeleteByCustomer_Call struct {
	*mock.Call
}

// DeleteByCustomer is a helper method to define mock.On call
//   - ctx context.Context
//   - customr customer.Customer
func (_e *InvoiceService_Expecter) DeleteByCustomer(ctx interface{}, customr interface{}) *InvoiceService_DeleteByCustomer_Call {
	return &InvoiceService_DeleteByCustomer_Call{Call: _e.mock.On("DeleteByCustomer", ctx, customr)}
}

func (_c *InvoiceService_DeleteByCustomer_Call) Run(run func(ctx context.Context, customr customer.Customer)) *InvoiceService_DeleteByCustomer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(customer.Customer))
	})
	return _c
}

func (_c *InvoiceService_DeleteByCustomer_Call) Return(_a0 error) *InvoiceService_DeleteByCustomer_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *InvoiceService_DeleteByCustomer_Call) RunAndReturn(run func(context.Context, customer.Customer) error) *InvoiceService_DeleteByCustomer_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, flt
func (_m *InvoiceService) List(ctx context.Context, flt invoice.Filter) ([]invoice.Invoice, error) {
	ret := _m.Called(ctx, flt)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []invoice.Invoice
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, invoice.Filter) ([]invoice.Invoice, error)); ok {
		return rf(ctx, flt)
	}
	if rf, ok := ret.Get(0).(func(context.Context, invoice.Filter) []invoice.Invoice); ok {
		r0 = rf(ctx, flt)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]invoice.Invoice)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, invoice.Filter) error); ok {
		r1 = rf(ctx, flt)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// InvoiceService_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type InvoiceService_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - flt invoice.Filter
func (_e *InvoiceService_Expecter) List(ctx interface{}, flt interface{}) *InvoiceService_List_Call {
	return &InvoiceService_List_Call{Call: _e.mock.On("List", ctx, flt)}
}

func (_c *InvoiceService_List_Call) Run(run func(ctx context.Context, flt invoice.Filter)) *InvoiceService_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(invoice.Filter))
	})
	return _c
}

func (_c *InvoiceService_List_Call) Return(_a0 []invoice.Invoice, _a1 error) *InvoiceService_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *InvoiceService_List_Call) RunAndReturn(run func(context.Context, invoice.Filter) ([]invoice.Invoice, error)) *InvoiceService_List_Call {
	_c.Call.Return(run)
	return _c
}

// NewInvoiceService creates a new instance of InvoiceService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewInvoiceService(t interface {
	mock.TestingT
	Cleanup(func())
}) *InvoiceService {
	mock := &InvoiceService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
