package domain

import (
	"context"
	"crypto/rand"
	"encoding/base64"
	"errors"
	"fmt"
	"net"
	"slices"
	"strings"
	"time"

	auditmodels "github.com/raystack/frontier/core/auditrecord/models"
	"github.com/raystack/frontier/core/membership"
	"github.com/raystack/frontier/core/organization"
	pkgauditrecord "github.com/raystack/frontier/pkg/auditrecord"
	"github.com/raystack/frontier/pkg/utils"

	"log/slog"

	"github.com/raystack/frontier/core/authenticate"
	"github.com/raystack/frontier/core/user"
	"github.com/raystack/frontier/internal/bootstrap/schema"
	"github.com/robfig/cron/v3"
)

type UserService interface {
	GetByID(ctx context.Context, id string) (user.User, error)
}

type OrgService interface {
	Get(ctx context.Context, id string) (organization.Organization, error)
	GetRaw(ctx context.Context, id string) (organization.Organization, error)
}

type MembershipService interface {
	AddOrganizationMember(ctx context.Context, orgID, principalID, principalType, roleID string) error
	ListResourcesByPrincipal(ctx context.Context, principal authenticate.Principal, resourceType string, filter membership.ResourceFilter) ([]string, error)
}

type AuditRecordRepository interface {
	Create(ctx context.Context, auditRecord auditmodels.AuditRecord) (auditmodels.AuditRecord, error)
}

type Service struct {
	repository            Repository
	userService           UserService
	orgService            OrgService
	membershipService     MembershipService
	auditRecordRepository AuditRecordRepository
	cron                  *cron.Cron
	log                   *slog.Logger
}

const (
	DNSChallenge       = "_frontier-domain-verification=%s"
	txtLength          = 40
	DefaultTokenExpiry = time.Hour * 24 * 7 // 7 days
	refreshTime        = "0 0 * * *"        // Once a day at midnight (UTC)
)

func NewService(logger *slog.Logger, repository Repository, userService UserService, orgService OrgService, membershipService MembershipService, auditRecordRepository AuditRecordRepository) *Service {
	return &Service{
		repository:            repository,
		userService:           userService,
		orgService:            orgService,
		membershipService:     membershipService,
		auditRecordRepository: auditRecordRepository,
		cron:                  cron.New(),
		log:                   logger,
	}
}

// Get an organization's whitelisted domain from the database
func (s Service) Get(ctx context.Context, id string) (Domain, error) {
	return s.repository.Get(ctx, id)
}

// List all whitelisted domains for an organization (filter by verified boolean)
func (s Service) List(ctx context.Context, flt Filter) ([]Domain, error) {
	return s.repository.List(ctx, flt)
}

// Delete marks an organization's whitelisted domain as deleted and writes an audit record
func (s Service) Delete(ctx context.Context, id string) error {
	dmn, err := s.repository.Get(ctx, id)
	if err != nil {
		return err
	}
	org, err := s.orgService.GetRaw(ctx, dmn.OrgID)
	if err != nil {
		return err
	}
	if err = s.repository.Delete(ctx, id); err != nil {
		return err
	}

	s.createAuditRecord(ctx, pkgauditrecord.DomainDeletedEvent, dmn, org)
	return nil
}

func (s Service) createAuditRecord(ctx context.Context, event pkgauditrecord.Event, dmn Domain, org organization.Organization) {
	if _, err := s.auditRecordRepository.Create(ctx, auditmodels.AuditRecord{
		Event: event,
		Resource: auditmodels.Resource{
			ID:   org.ID,
			Type: pkgauditrecord.OrganizationType,
			Name: org.Title,
		},
		Target: &auditmodels.Target{
			ID:   dmn.ID,
			Type: pkgauditrecord.DomainType,
			Name: dmn.Name,
		},
		OrgID:      org.ID,
		OrgName:    org.Title,
		OccurredAt: time.Now(),
	}); err != nil {
		s.log.WarnContext(ctx, "failed to create domain audit record",
			"event", event, "org_id", org.ID, "domain_id", dmn.ID, "domain_name", dmn.Name, "err", err)
	}
}

// Creates a record for the domain in the database and returns the TXT record that needs to be added to the DNS for the domain verification
func (s Service) Create(ctx context.Context, domain Domain) (Domain, error) {
	orgResp, err := s.orgService.Get(ctx, domain.OrgID)
	if err != nil {
		return Domain{}, err
	}

	txtRecord, err := generateRandomTXT()
	if err != nil {
		return Domain{}, err
	}

	domain.OrgID = orgResp.ID // in case the orgName is provided in the request, replace with the orgID
	domain.Token = fmt.Sprintf(DNSChallenge, txtRecord)
	var domainResp Domain
	if domainResp, err = s.repository.Create(ctx, domain); err != nil {
		return Domain{}, err
	}

	return domainResp, nil
}

// VerifyDomain checks if the TXT record for the domain matches the token generated by Frontier for the domain verification
func (s Service) VerifyDomain(ctx context.Context, id string) (Domain, error) {
	domain, err := s.repository.Get(ctx, id)
	if err != nil {
		return Domain{}, ErrNotExist
	}

	txtRecords, err := net.LookupTXT(domain.Name)
	if err != nil {
		if strings.Contains(err.Error(), "no such host") {
			return Domain{}, ErrInvalidDomain
		}
		return Domain{}, err
	}

	for _, txtRecord := range txtRecords {
		if strings.TrimSpace(txtRecord) == strings.TrimSpace(domain.Token) {
			domain.State = Verified
			domain, err = s.repository.Update(ctx, domain)
			if err != nil {
				return Domain{}, err
			}
			return domain, nil
		}
	}

	return domain, ErrTXTrecordNotFound
}

// Join an organization as a member if the user domain matches the org whitelisted domains
func (s Service) Join(ctx context.Context, orgID string, userId string) error {
	orgResp, err := s.orgService.Get(ctx, orgID)
	if err != nil {
		return err
	}

	currUser, err := s.userService.GetByID(ctx, userId)
	if err != nil {
		return err
	}

	userDomain := utils.ExtractDomainFromEmail(currUser.Email)
	if userDomain == "" {
		return user.ErrInvalidEmail
	}

	// check if user domain matches the org whitelisted domains
	orgTrustedDomains, err := s.List(ctx, Filter{
		OrgID: orgResp.ID,
		State: Verified,
	})
	if err != nil {
		return err
	}

	for _, dmn := range orgTrustedDomains {
		if userDomain == dmn.Name {
			// AddOrganizationMember checks if user is already a member and
			// returns ErrAlreadyMember — treat that as success (nothing to do)
			err = s.membershipService.AddOrganizationMember(ctx, orgResp.ID, currUser.ID, schema.UserPrincipal, schema.RoleOrganizationViewer)
			if err != nil && !errors.Is(err, membership.ErrAlreadyMember) {
				return err
			}
			return nil
		}
	}

	return ErrDomainsMisMatch
}

func (s Service) ListJoinableOrgsByDomain(ctx context.Context, email string) ([]string, error) {
	domain := utils.ExtractDomainFromEmail(email)
	domains, err := s.repository.List(ctx, Filter{
		Name:  domain,
		State: Verified,
	})
	if err != nil {
		return nil, err
	}

	// check if user is already a member of the organization. if yes, do not include the org in the response
	currUser, err := s.userService.GetByID(ctx, email)
	if err != nil {
		return nil, err
	}

	memberOrgIDs, err := s.membershipService.ListResourcesByPrincipal(ctx, authenticate.Principal{
		ID:   currUser.ID,
		Type: schema.UserPrincipal,
	}, schema.OrganizationNamespace, membership.ResourceFilter{})
	if err != nil {
		return nil, err
	}

	var orgIDs []string
	for _, domain := range domains {
		if !slices.Contains(memberOrgIDs, domain.OrgID) {
			orgIDs = append(orgIDs, domain.OrgID)
		}
	}
	return orgIDs, nil
}

// InitDomainVerification starts a cron job that runs once a day to delete expired domain requests which are still in pending state after 7 days of creation
func (s Service) InitDomainVerification(ctx context.Context) error {
	_, err := s.cron.AddFunc(refreshTime, func() {
		if err := s.repository.DeleteExpiredDomainRequests(ctx); err != nil {
			s.log.WarnContext(ctx, "error deleting expired domain requests", "err", err)
		}
	})
	if err != nil {
		return err
	}
	s.cron.Start()
	return nil
}

func (s Service) Close() error {
	return s.cron.Stop().Err()
}

func generateRandomTXT() (string, error) {
	randomBytes := make([]byte, txtLength)
	_, err := rand.Read(randomBytes)
	if err != nil {
		return "", err
	}

	// Encode the random bytes in Base64
	txtRecord := base64.StdEncoding.EncodeToString(randomBytes)
	return txtRecord, nil
}
